using System;
using System.Collections.Generic;

namespace ARCHi.Port
{
    public enum ArenaMove { Pulse, Guard, Signature }
    public enum ArenaField { Guardian, Scout }

    /// <summary>
    /// Session-only, aligned 1v1 subset of src/battle-engine.ts schema 1.
    /// Exact retained rules: 36 integrity, 3 Spark, concentration 2 + alignment 1,
    /// simultaneous resolution, exposure consumed only by incoming damage, 20 rounds.
    /// No Journey writes, mastery certification, model inference or item stat bonuses.
    /// Editor checks compare trajectories generated by the actual TypeScript engine.
    /// </summary>
    public sealed class ArenaRehearsal
    {
        private readonly List<ArenaMove> actions = new List<ArenaMove>();
        private object commandOwner;
        public IReadOnlyList<ArenaMove> Actions => actions.AsReadOnly();
        public int Round { get; private set; } = 1;
        public int Integrity { get; private set; } = 36;
        public int RivalIntegrity { get; private set; } = 36;
        public int Spark { get; private set; } = 3;
        public int RivalSpark { get; private set; } = 3;
        public bool Exposed { get; private set; }
        public bool RivalExposed { get; private set; }
        public string Winner { get; private set; } = "";
        public ArenaField Field { get; }
        public ArenaField RivalField => Field == ArenaField.Guardian ? ArenaField.Scout : ArenaField.Guardian;
        public bool Complete => Winner.Length > 0;
        public string Feedback { get; private set; } = "Read the field. Choose a move; both actions resolve together.";
        public int Absorbed { get; private set; }
        public int DamageTaken { get; private set; }
        public int DamageDealt { get; private set; }
        public ArenaMove LastRivalMove { get; private set; }
        public ArenaMove LastMove { get; private set; }
        public int GuardedRounds { get; private set; }
        public int ScoutedRounds { get; private set; }
        public bool UsesAutomaticOpponent { get; private set; } = true;

        public ArenaRehearsal(ArenaField field)
        {
            if (!Enum.IsDefined(typeof(ArenaField), field)) throw new ArgumentOutOfRangeException(nameof(field));
            Field = field;
        }

        public ArenaMove RivalChoice()
        {
            if (Complete) throw new InvalidOperationException("The rehearsal is complete.");
            if (Integrity <= 7) return ArenaMove.Pulse;
            var hurt = RivalIntegrity <= 24;
            if (RivalSpark > 0)
            {
                var damage = RivalField == ArenaField.Guardian ? 5 : 6;
                if (damage >= Integrity) return ArenaMove.Signature;
                if (RivalField == ArenaField.Scout && !Exposed && Round % 3 == 1) return ArenaMove.Signature;
                if (RivalField == ArenaField.Guardian && (Round % 3 == 1 || hurt || RivalExposed)) return ArenaMove.Signature;
            }
            return Round % 3 == 0 && Round < 20 && (hurt || RivalExposed) ? ArenaMove.Guard : ArenaMove.Pulse;
        }

        public bool Resolve(ArenaMove move, int expectedRound)
        {
            if (commandOwner != null || !CanResolve(move, Spark, expectedRound)) return false;
            return ResolveMoves(move, RivalChoice(), expectedRound, true);
        }

        /// <summary>Same simultaneous rules, with two deliberate choices rather than the ECHO policy.</summary>
        public bool ResolvePair(ArenaMove one, ArenaMove two, int expectedRound)
        {
            return commandOwner == null && ResolveMoves(one, two, expectedRound, false);
        }

        internal void ClaimCommands(object owner)
        {
            if (owner == null || commandOwner != null || actions.Count != 0)
                throw new InvalidOperationException("Only a fresh rehearsal can belong to a session.");
            commandOwner = owner;
            UsesAutomaticOpponent = false;
        }

        internal bool ResolveOwnedPair(object owner, ArenaMove one, ArenaMove two, int expectedRound)
        {
            return owner != null && ReferenceEquals(owner, commandOwner) && ResolveMoves(one, two, expectedRound, false);
        }

        private bool CanResolve(ArenaMove move, int spark, int expectedRound)
        {
            return Enum.IsDefined(typeof(ArenaMove), move) && !Complete && expectedRound == Round &&
                (move != ArenaMove.Signature || spark > 0);
        }

        private bool ResolveMoves(ArenaMove move, ArenaMove rival, int expectedRound, bool automatic)
        {
            // Validate both choices before touching either participant's state.
            if (!CanResolve(move, Spark, expectedRound) || !CanResolve(rival, RivalSpark, expectedRound)) return false;
            UsesAutomaticOpponent &= automatic;
            int hit = Power(move, Field), rivalHit = Power(rival, RivalField);
            int shield = Shield(move, Field), rivalShield = Shield(rival, RivalField);
            int incoming = rivalHit + (Exposed && rivalHit > 0 ? 3 : 0);
            int outgoing = hit + (RivalExposed && hit > 0 ? 3 : 0);
            Absorbed = Math.Min(shield, incoming);
            DamageTaken = Math.Max(0, incoming - shield);
            DamageDealt = Math.Max(0, outgoing - rivalShield);
            Integrity = Math.Max(0, Integrity - DamageTaken);
            RivalIntegrity = Math.Max(0, RivalIntegrity - DamageDealt);
            if (Exposed && rivalHit > 0) Exposed = false;
            if (RivalExposed && hit > 0) RivalExposed = false;
            if (move == ArenaMove.Signature) { Spark--; if (Field == ArenaField.Scout && RivalIntegrity > 0) RivalExposed = true; }
            if (rival == ArenaMove.Signature) { RivalSpark--; if (RivalField == ArenaField.Scout && Integrity > 0) Exposed = true; }
            if (Absorbed > 0) GuardedRounds++;
            if (move == ArenaMove.Signature && Field == ArenaField.Scout && RivalIntegrity > 0) ScoutedRounds++;
            LastMove = move; LastRivalMove = rival;
            Feedback = $"Round {Round} · {move} / {rival}. Dealt {DamageDealt}, received {DamageTaken}, protected {Absorbed}.";
            if (Integrity == 0 && RivalIntegrity == 0) Winner = "draw";
            else if (Integrity == 0) Winner = "two";
            else if (RivalIntegrity == 0) Winner = "one";
            else if (Round >= 20)
                Winner = Integrity != RivalIntegrity ? (Integrity > RivalIntegrity ? "one" : "two") : Spark != RivalSpark ? (Spark > RivalSpark ? "one" : "two") : "draw";
            actions.Add(move);
            Round++;
            return true;
        }

        private static int Power(ArenaMove move, ArenaField field) => move == ArenaMove.Pulse ? 7 : move == ArenaMove.Signature ? (field == ArenaField.Guardian ? 5 : 6) : 0;
        private static int Shield(ArenaMove move, ArenaField field) => move == ArenaMove.Guard || (move == ArenaMove.Signature && field == ArenaField.Guardian) ? 7 : 0;
    }

    /// <summary>Reviewed facts about this disposable exercise. This is not a saved KIN knowledge store.</summary>
    public sealed class ArenaLearningPreview
    {
        private readonly HashSet<ArenaRehearsal> reviewed = new HashSet<ArenaRehearsal>();
        public int GuardianEvidence { get; private set; }
        public int ScoutEvidence { get; private set; }
        public int ReviewedBouts => reviewed.Count;
        public ArenaExperience Latest { get; private set; }
        public string Lesson { get; private set; } = "Finish a bout, then review what the recorded actions actually demonstrated.";
        public bool Review(ArenaRehearsal bout)
        {
            if (bout == null || !bout.UsesAutomaticOpponent || reviewed.Contains(bout)) return false;
            var experience = ArenaExperience.FromCompleted(bout);
            if (experience == null || !reviewed.Add(bout)) return false;
            GuardianEvidence += bout.GuardedRounds;
            ScoutEvidence += bout.ScoutedRounds;
            Latest = experience;
            Lesson = experience.Explanation;
            return true;
        }
    }
}
