import copy
import unittest

from marketplace.model import (APIError, MAX_BODY, json_bytes, parse_json, validate_recipe,
                               validate_provenance, password_value)
from marketplace.tests.fixtures import recipe, provenance


class RecipeTests(unittest.TestCase):
    def test_native_golden_fingerprint_and_json_independence(self):
        # Existing Swift golden vector, not an expectation generated by this service.
        value = recipe("Focus Staff", creator="Hampton", summary="A pearl of lilac light. Point gently to a selected passage.",
                       license="MIT", palette="lilac", crown="pearl", action="pointSelection")
        digest = validate_recipe(value)[1]
        self.assertEqual(digest, "d20c3825dc05fc7f7603ae2d7b7cd01f7053ebd0b82eba5a251eb4d8dc0a36f0")
        reordered = dict(reversed(list(value.items())))
        self.assertEqual(validate_recipe(parse_json(json_bytes(reordered)))[1], digest)

    def test_each_field_participates_in_fingerprint(self):
        value = recipe()
        original = validate_recipe(value)[1]
        changes = {"title": "Another Staff", "creator": "Another Artist", "summary": "Another summary",
                   "revision": 2, "license": "MIT", "palette": "rose", "crown": "star", "action": "pointSelection"}
        for key, replacement in changes.items():
            with self.subTest(key=key):
                changed = dict(value, **{key: replacement})
                self.assertNotEqual(validate_recipe(changed)[1], original)
        for key, replacement in (("pace", "Quick"), ("sparkle", "Bright"), ("hold", "Lingering")):
            with self.subTest(gesture=key):
                changed = copy.deepcopy(value)
                changed["defaultGesture"][key] = replacement
                self.assertNotEqual(validate_recipe(changed)[1], original)

    def test_utf16_limits_and_unambiguous_field_boundaries(self):
        validate_recipe(recipe("🌱" * 12))
        with self.assertRaises(APIError):
            validate_recipe(recipe("🌱" * 13))
        self.assertNotEqual(validate_recipe(recipe("ab", creator="c"))[1],
                            validate_recipe(recipe("a", creator="bc"))[1])

    def test_closed_shapes_and_no_executable_fields(self):
        for extra in ("id", "effects", "assetURL", "price", "balance", "script", "publisher", "isRegistered"):
            with self.subTest(extra=extra), self.assertRaises(APIError):
                validate_recipe(recipe(**{extra: "untrusted"}))
        value = recipe()
        for key in value:
            changed = dict(value)
            del changed[key]
            with self.subTest(missing=key), self.assertRaises(APIError):
                validate_recipe(changed)
        value["defaultGesture"]["script"] = "anything"
        with self.assertRaises(APIError):
            validate_recipe(value)

    def test_invalid_enums_revision_types_and_controls(self):
        for name, values in {"schema": ["v2", None], "revision": [True, 0, 1000, 1.0, "1"],
                             "license": ["proprietary", []], "action": ["damage+100", "execute"],
                             "title": [" ", "tab\tname", "line\u2028name", "control\u0085", "x" * 25],
                             "creator": ["x" * 49], "summary": ["x" * 161]}.items():
            for replacement in values:
                with self.subTest(name=name, replacement=replacement), self.assertRaises(APIError):
                    validate_recipe(recipe(**{name: replacement}))

    def test_attribution_and_license_permission_are_explicit(self):
        validate_provenance(provenance())
        validate_provenance(provenance(declaration="licensed-adaptation", source="Synthetic source catalog"))
        for changes in ({"rightsConfirmed": False}, {"rightsConfirmed": 1}, {"attribution": ""},
                        {"declaration": "verified"}, {"declaration": "licensed-adaptation"}, {"source": "x" * 501}):
            with self.subTest(changes=changes), self.assertRaises(APIError):
                validate_provenance(provenance(**changes))

    def test_json_rejects_duplicate_keys_including_escape_aliases(self):
        for raw in (b'{"a":1,"a":2}', b'{"a":1,"\\u0061":2}', b'{"nested":{"a":1,"a":2}}',
                    b'{"v":NaN}', b'{"v":Infinity}', b'{"v":1e400}', b'{"v":"\\ud800"}', b'{"v":"\xff"}',
                    b"[" * 12 + b"0" + b"]" * 12, b"{incomplete"):
            with self.subTest(raw=raw), self.assertRaises(APIError) as caught:
                parse_json(raw)
            self.assertEqual(caught.exception.status, 400)

    def test_oversized_body_and_password_rejection(self):
        with self.assertRaises(APIError) as caught:
            parse_json(b" " * (MAX_BODY + 1))
        self.assertEqual(caught.exception.status, 413)
        for password in ("short", "x" * 129, "a" * 15 + "\n", "\ud800" * 12):
            with self.subTest(password=repr(password)), self.assertRaises(APIError):
                password_value(password)
        self.assertEqual(len(password_value("😀" * 128)), 512)


if __name__ == "__main__":
    unittest.main()
